"-----BEGIN PRIVATE KEY-----\n
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/XitR5jac4m4+rCU
cvTc1/3lgGjEM6flKGAywXTW1F2gCgYIKoZIzj0DAQehRANCAASyH0/2ivHKTK3i
PiY+avDX7qQUpFeW6eOh/Au2dSbV76FXRFmdujxQsFMmwZOkntlDnGtzYBnUB2go
y1dJCNbh\n
-----END PRIVATE KEY-----"