fastlane_version "2.213.0" # Replace with the desired Fastlane version
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do

    desc "Set Info.plist Version and Build Number"
    lane :set_full_version do
        version = flutter_version()

        increment_version_number(version_number: version['version_name'])

        increment_build_number(build_number: version['version_code'])
      end


  desc "Description of what the lane does"
  lane :deploy do
    set_full_version()
    setup_ci if is_ci
    cocoapods(clean_install: is_ci)

    gym(
      silent: true,
      suppress_xcode_output: true,
    )
    match(
      type: "appstore",
      readonly: is_ci,
     )
    sync_code_signing
    disable_automatic_code_signing(path: "Runner.xcodeproj")

    build_app(
      xcargs: "-allowProvisioningUpdates",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      archive_path: "../build/ios/Runner.xcarchive",
      output_directory: "../build/ios/Runner",
    )

    enable_automatic_code_signing(path: "Runner.xcodeproj")


    upload_to_testflight(
      api_key_path: "../ios/fastlane/app_store_connect.json",
      ipa: '../build/ios/Runner/Runner.ipa',
      skip_waiting_for_build_processing: true,
    )

  end
end



