fastlane_version "2.213.0" # Replace with the desired Fastlane version
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do

    desc "Set Info.plist Version and Build Number"
    lane :set_full_version do
        version = flutter_version()

        increment_version_number(version_number: version['version_name'])

        increment_build_number(build_number: version['version_code'])
      end


  desc "Description of what the lane does"
  lane :deploy do
    set_full_version()
    setup_ci if is_ci

    cocoapods(clean_install: is_ci)


    match(
      type: "appstore",
      readonly: is_ci,
    )


    build_app(
      xcargs: "-allowProvisioningUpdates",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      archive_path: "../build/ios/Runner.xcarchive",
      output_directory: "../build/ios/Runner",
    )

    upload_to_testflight(
      api_key_path: "../ios/fastlane/app_store_connect.json",
      ipa: '../build/ios/Runner/Runner.ipa',
      skip_waiting_for_build_processing: true,
    )



       # add actions here: https://docs.fastlane.tools/actions
#       get_certificates()           # invokes cert
#        get_provisioning_profile(readonly:true)   # invokes sigh

#        increment_build_number(
#         build_number: "4" # set a specific number
#        )

#        gym(
#           scheme: 'Runner',
#           export_method: 'app-store'
#         )
#        match(
#             type: "appstore",
#             readonly: is_ci,
#           )
#
#       api_key = app_store_connect_api_key(
#           key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/XitR5jac4m4+rCUcvTc1/3lgGjEM6flKGAywXTW1F2gCgYIKoZIzj0DAQehRANCAASyH0/2ivHKTK3iPiY+avDX7qQUpFeW6eOh/Au2dSbV76FXRFmdujxQsFMmwZOkntlDnGtzYBnUB2goy1dJCNbh\n-----END PRIVATE KEY-----",
#           is_key_content_base64: 'false',
#           key_id: "4T6C59FKR7",
#           issuer_id: "69a6de8d-aed7-47e3-e053-5b8c7c11a4d1",
#           duration: 1200, # optional (maximum 1200)
#           in_house: false # optional but may be required if using match/sigh
#         )
#
#     pilot(api_key: api_key)
#
#

#       upload_to_testflight(
#         api_key: api_key,
#         skip_submission: true,
#         skip_waiting_for_build_processing: true,
#       )

#
#
#     # add actions here: https://docs.fastlane.tools/actions
#     get_certificates()           # invokes cert
#     get_provisioning_profile()   # invokes sigh
#
#
#     enable_automatic_code_signing(
#         path: "test-automated-build/ios/Runner.xcodeproj",
#
#      )
#
#
#       build_app(
#       scheme: "Runner",
#       export_method: "app-store",
#       export_xcargs: "-allowProvisioningUpdates",
#       export_options: {
#           manageAppVersionAndBuildNumber: false,
#           provisioningProfiles: {
#          'com.app.cicd' => 'TestCICD_Dis.mobileprovision',
#          }
#         }
#      )
#     upload_to_testflight(
#     username: ENV["FASTLANE_USER"],
#
#     )


  end
end



